### PR TITLE
Update for PureScript 0.10.1

### PR DESCRIPTION
**Pull request by menelaos**

### CODE REVIEW

**Comment by menelaos** [comment]
Unfortunately, the maintainer of `purescript-var` has not yet updated the dependencies. The latest commit in `master` does work with the newest packages though.

**Comment by eskimor** [comment]
Thanks! :-)

**Comment by eskimor** [comment]
I presume it really works with psc-0.10.1? :-) I can't test right now.

**Comment by menelaos** [comment]
Well, it compiles and the tests pass :-)
The latest commit in `purescript-var` (which  is referenced in this PR) added functional dependencies: 
https://github.com/zudov/purescript-var/commit/dc6238dbc20af0e3d53a5397b57c4c96b7040180

**Comment by eskimor** [comment]
good enough! :-)

**Pull request merged**
