### PR TITLE
[WIP] Add mock storage

### LINKED ISSUE #2: Mock storage
Would it make sense to provide a mock `Storage` that just saves to a `Foreign` for testing?

### PR DESCRIPTION
**Pull request by texastoland**
Don't merge yet…

Fix #2. Needs tests.

### CODE REVIEW

**Comment by eskimor** [comment]
Very nice - my first PR on this project :-) Definitely going to be merged, just tell me when it is ready and I will have a look again. (I am not able to do so in the following week, but afterwards expect a promptly merge)

**Comment by texastoland** [comment]
I'll let you know! I have a few other PRs in progress so that's my timeframe as well.

**Comment by eskimor** [comment]
Since when do we have travis on this project? I like :-)

**Comment by texastoland** [comment]
I'm going to rebase this on a couple other branches for my current project.

**Comment by texastoland** [comment]
I'm going to resurrect this in a separate PR.

**Pull request closed without merging**
